// Code generated by protoc-gen-go. DO NOT EDIT.
// source: srv.user.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserServerRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserServerRequest) Reset()         { *m = UserServerRequest{} }
func (m *UserServerRequest) String() string { return proto.CompactTextString(m) }
func (*UserServerRequest) ProtoMessage()    {}
func (*UserServerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_26d10fc4f266bb1e, []int{0}
}

func (m *UserServerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserServerRequest.Unmarshal(m, b)
}
func (m *UserServerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserServerRequest.Marshal(b, m, deterministic)
}
func (m *UserServerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserServerRequest.Merge(m, src)
}
func (m *UserServerRequest) XXX_Size() int {
	return xxx_messageInfo_UserServerRequest.Size(m)
}
func (m *UserServerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserServerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserServerRequest proto.InternalMessageInfo

func (m *UserServerRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UserServerResponse struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserServerResponse) Reset()         { *m = UserServerResponse{} }
func (m *UserServerResponse) String() string { return proto.CompactTextString(m) }
func (*UserServerResponse) ProtoMessage()    {}
func (*UserServerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_26d10fc4f266bb1e, []int{1}
}

func (m *UserServerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserServerResponse.Unmarshal(m, b)
}
func (m *UserServerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserServerResponse.Marshal(b, m, deterministic)
}
func (m *UserServerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserServerResponse.Merge(m, src)
}
func (m *UserServerResponse) XXX_Size() int {
	return xxx_messageInfo_UserServerResponse.Size(m)
}
func (m *UserServerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserServerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserServerResponse proto.InternalMessageInfo

func (m *UserServerResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*UserServerRequest)(nil), "proto.UserServerRequest")
	proto.RegisterType((*UserServerResponse)(nil), "proto.UserServerResponse")
}

func init() { proto.RegisterFile("srv.user.proto", fileDescriptor_26d10fc4f266bb1e) }

var fileDescriptor_26d10fc4f266bb1e = []byte{
	// 145 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x2e, 0x2a, 0xd3,
	0x2b, 0x2d, 0x4e, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0xea,
	0x5c, 0x82, 0xa1, 0xc5, 0xa9, 0x45, 0xc1, 0xa9, 0x45, 0x65, 0xa9, 0x45, 0x41, 0xa9, 0x85, 0xa5,
	0xa9, 0xc5, 0x25, 0x42, 0x42, 0x5c, 0x2c, 0x79, 0x89, 0xb9, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a,
	0x9c, 0x41, 0x60, 0xb6, 0x92, 0x1a, 0x97, 0x10, 0xb2, 0xc2, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54,
	0x21, 0x01, 0x2e, 0xe6, 0xdc, 0xe2, 0x74, 0xa8, 0x42, 0x10, 0xd3, 0xc8, 0x93, 0x8b, 0xdd, 0xbd,
	0x28, 0x35, 0xb5, 0x24, 0xb5, 0x48, 0xc8, 0x8e, 0x8b, 0xd5, 0x23, 0x35, 0x27, 0x27, 0x5f, 0x48,
	0x02, 0x62, 0xa7, 0x1e, 0x86, 0x4d, 0x52, 0x92, 0x58, 0x64, 0x20, 0x46, 0x2b, 0x31, 0x24, 0xb1,
	0x81, 0xe5, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x78, 0xc9, 0x2f, 0x69, 0xbb, 0x00, 0x00,
	0x00,
}
