// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.11.4
// source: srv.user.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type LoginByUserNameRespErrors int32

const (
	LoginByUserNameResp_ERROR_NIL  LoginByUserNameRespErrors = 0 // 没有错误
	LoginByUserNameResp_ERROR_SYS  LoginByUserNameRespErrors = 1 // 一般错误
	LoginByUserNameResp_ERROR_USER LoginByUserNameRespErrors = 2 // 用户不存在
	LoginByUserNameResp_ERROR_PWD  LoginByUserNameRespErrors = 3 // 密码错误
)

// Enum value maps for LoginByUserNameRespErrors.
var (
	LoginByUserNameRespErrors_name = map[int32]string{
		0: "ERROR_NIL",
		1: "ERROR_SYS",
		2: "ERROR_USER",
		3: "ERROR_PWD",
	}
	LoginByUserNameRespErrors_value = map[string]int32{
		"ERROR_NIL":  0,
		"ERROR_SYS":  1,
		"ERROR_USER": 2,
		"ERROR_PWD":  3,
	}
)

func (x LoginByUserNameRespErrors) Enum() *LoginByUserNameRespErrors {
	p := new(LoginByUserNameRespErrors)
	*p = x
	return p
}

func (x LoginByUserNameRespErrors) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoginByUserNameRespErrors) Descriptor() protoreflect.EnumDescriptor {
	return file_srv_user_proto_enumTypes[0].Descriptor()
}

func (LoginByUserNameRespErrors) Type() protoreflect.EnumType {
	return &file_srv_user_proto_enumTypes[0]
}

func (x LoginByUserNameRespErrors) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoginByUserNameRespErrors.Descriptor instead.
func (LoginByUserNameRespErrors) EnumDescriptor() ([]byte, []int) {
	return file_srv_user_proto_rawDescGZIP(), []int{1, 0}
}

type LoginByUserNameReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username []byte `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password []byte `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *LoginByUserNameReq) Reset() {
	*x = LoginByUserNameReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_srv_user_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginByUserNameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginByUserNameReq) ProtoMessage() {}

func (x *LoginByUserNameReq) ProtoReflect() protoreflect.Message {
	mi := &file_srv_user_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginByUserNameReq.ProtoReflect.Descriptor instead.
func (*LoginByUserNameReq) Descriptor() ([]byte, []int) {
	return file_srv_user_proto_rawDescGZIP(), []int{0}
}

func (x *LoginByUserNameReq) GetUsername() []byte {
	if x != nil {
		return x.Username
	}
	return nil
}

func (x *LoginByUserNameReq) GetPassword() []byte {
	if x != nil {
		return x.Password
	}
	return nil
}

type LoginByUserNameResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrNo  LoginByUserNameRespErrors `protobuf:"varint,1,opt,name=err_no,json=errNo,proto3,enum=proto.LoginByUserNameRespErrors" json:"err_no,omitempty"`
	ErrMsg string                    `protobuf:"bytes,2,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
}

func (x *LoginByUserNameResp) Reset() {
	*x = LoginByUserNameResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_srv_user_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginByUserNameResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginByUserNameResp) ProtoMessage() {}

func (x *LoginByUserNameResp) ProtoReflect() protoreflect.Message {
	mi := &file_srv_user_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginByUserNameResp.ProtoReflect.Descriptor instead.
func (*LoginByUserNameResp) Descriptor() ([]byte, []int) {
	return file_srv_user_proto_rawDescGZIP(), []int{1}
}

func (x *LoginByUserNameResp) GetErrNo() LoginByUserNameRespErrors {
	if x != nil {
		return x.ErrNo
	}
	return LoginByUserNameResp_ERROR_NIL
}

func (x *LoginByUserNameResp) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

var File_srv_user_proto protoreflect.FileDescriptor

var file_srv_user_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x73, 0x72, 0x76, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4c, 0x0a, 0x12, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x70, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0xaf, 0x01, 0x0a, 0x13, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x42,
	0x79, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x38, 0x0a,
	0x06, 0x65, 0x72, 0x72, 0x5f, 0x6e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x42, 0x79, 0x55, 0x73, 0x65,
	0x72, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73,
	0x52, 0x05, 0x65, 0x72, 0x72, 0x4e, 0x6f, 0x12, 0x17, 0x0a, 0x07, 0x65, 0x72, 0x72, 0x5f, 0x6d,
	0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x4d, 0x73, 0x67,
	0x22, 0x45, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x12, 0x0d, 0x0a, 0x09, 0x45, 0x52,
	0x52, 0x4f, 0x52, 0x5f, 0x4e, 0x49, 0x4c, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x45, 0x52, 0x52,
	0x4f, 0x52, 0x5f, 0x53, 0x59, 0x53, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x45, 0x52, 0x52, 0x4f,
	0x52, 0x5f, 0x55, 0x53, 0x45, 0x52, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x45, 0x52, 0x52, 0x4f,
	0x52, 0x5f, 0x50, 0x57, 0x44, 0x10, 0x03, 0x32, 0x53, 0x0a, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x12, 0x4a, 0x0a, 0x0f, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x1a,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x42, 0x79, 0x55, 0x73,
	0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_srv_user_proto_rawDescOnce sync.Once
	file_srv_user_proto_rawDescData = file_srv_user_proto_rawDesc
)

func file_srv_user_proto_rawDescGZIP() []byte {
	file_srv_user_proto_rawDescOnce.Do(func() {
		file_srv_user_proto_rawDescData = protoimpl.X.CompressGZIP(file_srv_user_proto_rawDescData)
	})
	return file_srv_user_proto_rawDescData
}

var file_srv_user_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_srv_user_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_srv_user_proto_goTypes = []interface{}{
	(LoginByUserNameRespErrors)(0), // 0: proto.LoginByUserNameResp.errors
	(*LoginByUserNameReq)(nil),     // 1: proto.LoginByUserNameReq
	(*LoginByUserNameResp)(nil),    // 2: proto.LoginByUserNameResp
}
var file_srv_user_proto_depIdxs = []int32{
	0, // 0: proto.LoginByUserNameResp.err_no:type_name -> proto.LoginByUserNameResp.errors
	1, // 1: proto.Login.LoginByUserName:input_type -> proto.LoginByUserNameReq
	2, // 2: proto.Login.LoginByUserName:output_type -> proto.LoginByUserNameResp
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_srv_user_proto_init() }
func file_srv_user_proto_init() {
	if File_srv_user_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_srv_user_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginByUserNameReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_srv_user_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginByUserNameResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_srv_user_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_srv_user_proto_goTypes,
		DependencyIndexes: file_srv_user_proto_depIdxs,
		EnumInfos:         file_srv_user_proto_enumTypes,
		MessageInfos:      file_srv_user_proto_msgTypes,
	}.Build()
	File_srv_user_proto = out.File
	file_srv_user_proto_rawDesc = nil
	file_srv_user_proto_goTypes = nil
	file_srv_user_proto_depIdxs = nil
}
