// Code generated by protoc-gen-go. DO NOT EDIT.
// source: srv.user.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginByUserNameRespErrors int32

const (
	LoginByUserNameResp_ERROR_NIL  LoginByUserNameRespErrors = 0
	LoginByUserNameResp_ERROR_SYS  LoginByUserNameRespErrors = 1
	LoginByUserNameResp_ERROR_USER LoginByUserNameRespErrors = 2
	LoginByUserNameResp_ERROR_PWD  LoginByUserNameRespErrors = 3
)

var LoginByUserNameRespErrors_name = map[int32]string{
	0: "ERROR_NIL",
	1: "ERROR_SYS",
	2: "ERROR_USER",
	3: "ERROR_PWD",
}

var LoginByUserNameRespErrors_value = map[string]int32{
	"ERROR_NIL":  0,
	"ERROR_SYS":  1,
	"ERROR_USER": 2,
	"ERROR_PWD":  3,
}

func (x LoginByUserNameRespErrors) String() string {
	return proto.EnumName(LoginByUserNameRespErrors_name, int32(x))
}

func (LoginByUserNameRespErrors) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_26d10fc4f266bb1e, []int{1, 0}
}

type LoginByUserNameReq struct {
	Username             []byte   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             []byte   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginByUserNameReq) Reset()         { *m = LoginByUserNameReq{} }
func (m *LoginByUserNameReq) String() string { return proto.CompactTextString(m) }
func (*LoginByUserNameReq) ProtoMessage()    {}
func (*LoginByUserNameReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_26d10fc4f266bb1e, []int{0}
}

func (m *LoginByUserNameReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginByUserNameReq.Unmarshal(m, b)
}
func (m *LoginByUserNameReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginByUserNameReq.Marshal(b, m, deterministic)
}
func (m *LoginByUserNameReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginByUserNameReq.Merge(m, src)
}
func (m *LoginByUserNameReq) XXX_Size() int {
	return xxx_messageInfo_LoginByUserNameReq.Size(m)
}
func (m *LoginByUserNameReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginByUserNameReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginByUserNameReq proto.InternalMessageInfo

func (m *LoginByUserNameReq) GetUsername() []byte {
	if m != nil {
		return m.Username
	}
	return nil
}

func (m *LoginByUserNameReq) GetPassword() []byte {
	if m != nil {
		return m.Password
	}
	return nil
}

type LoginByUserNameResp struct {
	ErrNo                LoginByUserNameRespErrors `protobuf:"varint,1,opt,name=err_no,json=errNo,proto3,enum=proto.LoginByUserNameRespErrors" json:"err_no,omitempty"`
	ErrMsg               string                    `protobuf:"bytes,2,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *LoginByUserNameResp) Reset()         { *m = LoginByUserNameResp{} }
func (m *LoginByUserNameResp) String() string { return proto.CompactTextString(m) }
func (*LoginByUserNameResp) ProtoMessage()    {}
func (*LoginByUserNameResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_26d10fc4f266bb1e, []int{1}
}

func (m *LoginByUserNameResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginByUserNameResp.Unmarshal(m, b)
}
func (m *LoginByUserNameResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginByUserNameResp.Marshal(b, m, deterministic)
}
func (m *LoginByUserNameResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginByUserNameResp.Merge(m, src)
}
func (m *LoginByUserNameResp) XXX_Size() int {
	return xxx_messageInfo_LoginByUserNameResp.Size(m)
}
func (m *LoginByUserNameResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginByUserNameResp.DiscardUnknown(m)
}

var xxx_messageInfo_LoginByUserNameResp proto.InternalMessageInfo

func (m *LoginByUserNameResp) GetErrNo() LoginByUserNameRespErrors {
	if m != nil {
		return m.ErrNo
	}
	return LoginByUserNameResp_ERROR_NIL
}

func (m *LoginByUserNameResp) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func init() {
	proto.RegisterEnum("proto.LoginByUserNameRespErrors", LoginByUserNameRespErrors_name, LoginByUserNameRespErrors_value)
	proto.RegisterType((*LoginByUserNameReq)(nil), "proto.LoginByUserNameReq")
	proto.RegisterType((*LoginByUserNameResp)(nil), "proto.LoginByUserNameResp")
}

func init() { proto.RegisterFile("srv.user.proto", fileDescriptor_26d10fc4f266bb1e) }

var fileDescriptor_26d10fc4f266bb1e = []byte{
	// 239 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x8f, 0x3f, 0x4b, 0xc4, 0x40,
	0x10, 0xc5, 0x2f, 0x27, 0x39, 0xbd, 0x41, 0x63, 0x18, 0x0b, 0xcf, 0x54, 0x9a, 0xca, 0x2a, 0xc5,
	0xd9, 0x58, 0x8b, 0x29, 0x94, 0x18, 0x65, 0xc2, 0x21, 0x56, 0x47, 0xc4, 0x21, 0x58, 0x24, 0x93,
	0x9b, 0xf1, 0x0f, 0x7e, 0x2a, 0xbf, 0xa2, 0xec, 0x06, 0x3d, 0x50, 0xaf, 0x5a, 0x1e, 0xef, 0xed,
	0x6f, 0x7f, 0x0b, 0x91, 0xe9, 0x5b, 0xf6, 0x6a, 0xac, 0x59, 0xaf, 0xf2, 0x22, 0x18, 0xfa, 0x23,
	0x2d, 0x00, 0x0b, 0x69, 0x9e, 0xbb, 0x8b, 0x8f, 0x85, 0xb1, 0x96, 0x75, 0xcb, 0xc4, 0x2b, 0x4c,
	0x60, 0xc7, 0x4d, 0xbb, 0xba, 0xe5, 0x59, 0x70, 0x1c, 0x9c, 0xee, 0xd2, 0x4f, 0x76, 0x5d, 0x5f,
	0x9b, 0xbd, 0x8b, 0x3e, 0xcd, 0xc6, 0x43, 0xf7, 0x9d, 0xd3, 0xcf, 0x00, 0x0e, 0xfe, 0xe0, 0xac,
	0xc7, 0x73, 0x98, 0xb0, 0xea, 0xb2, 0x13, 0x4f, 0x8b, 0xe6, 0x27, 0x83, 0x44, 0xf6, 0xcf, 0x36,
	0x63, 0x55, 0x51, 0xa3, 0x90, 0x55, 0x4b, 0xc1, 0x43, 0xd8, 0x76, 0x37, 0x5b, 0x6b, 0xfc, 0x63,
	0x53, 0x72, 0xa0, 0x1b, 0x6b, 0xd2, 0xdc, 0x23, 0x45, 0x0d, 0xf7, 0x60, 0x9a, 0x13, 0xdd, 0xd2,
	0xb2, 0xbc, 0x2a, 0xe2, 0xd1, 0x3a, 0x56, 0x0f, 0x55, 0x1c, 0x60, 0x04, 0x30, 0xc4, 0x45, 0x95,
	0x53, 0x3c, 0x5e, 0xd7, 0x77, 0xf7, 0x97, 0xf1, 0xd6, 0xbc, 0x82, 0xd0, 0x4b, 0xe0, 0x35, 0xec,
	0xff, 0xb2, 0xc1, 0xa3, 0x4d, 0x96, 0xab, 0x24, 0xd9, 0xfc, 0x81, 0x74, 0xf4, 0x38, 0xf1, 0xe5,
	0xd9, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x99, 0x60, 0xa9, 0x4b, 0x74, 0x01, 0x00, 0x00,
}
